"""Bibliography for the PhD thesis (numbered references)."""

TITLE = "References"

# Only references cited in the thesis body (contiguous numbering).
# Each entry: (authors, title, venue, year, optional_url_or_doi)
REFERENCES = [
    ('Rescorla, E.', 'The Transport Layer Security (TLS) Protocol Version 1.3', 'RFC 8446, IETF', '2018'),
    ('Dworkin, M.', 'Recommendation for Block Cipher Modes of Operation: Galois/Counter Mode (GCM)', 'NIST SP 800-38D', '2007'),
    ('Barker, E.', 'Recommendation for Key Management: Part 1 — General', 'NIST SP 800-57 Part 1 Rev. 5', '2020'),
    ('Cooper, D. et al.', 'Internet X.509 Public Key Infrastructure Certificate and CRL Profile', 'RFC 5280, IETF', '2008'),
    ('Krawczyk, H.', 'Cryptographic Extraction and Key Derivation: The HKDF Scheme', 'CRYPTO 2010, LNCS', '2010'),
    ('Krawczyk, H.', 'HMAC-based Extract-and-Expand Key Derivation Function (HKDF)', 'RFC 5869, IETF', '2010'),
    ('Bellare, M.; Rogaway, P.', 'Entity Authentication and Key Distribution', 'CRYPTO 1993, LNCS', '1993'),
    ('Canetti, R.; Krawczyk, H.', 'Analysis of Key-Exchange Protocols and Their Use for Building Secure Channels', 'EUROCRYPT 2001, LNCS', '2001'),
    ('Johnson, D.; Menezes, A.; Vanstone, S.', 'The Elliptic Curve Digital Signature Algorithm (ECDSA)', 'International Journal of Information Security', '2001'),
    ('Bernstein, D. J. et al.', 'Edwards-Curve Digital Signature Algorithm (EdDSA)', 'RFC 8032, IETF', '2017'),
    ('SECG', 'SEC 1: Elliptic Curve Cryptography, Version 2.0', 'Standards for Efficient Cryptography Group', '2010'),
    ('ANSI', 'Public Key Cryptography for the Financial Services Industry: Key Agreement Using Diffie-Hellman', 'ANSI X9.63', '2011'),
    ('Hardt, D.', 'The OAuth 2.0 Authorization Framework', 'RFC 6749, IETF', '2012'),
    ('Lodderstedt, T. et al.', 'OAuth 2.0 for Native Apps (PKCE)', 'RFC 8252, IETF', '2017'),
    ('Barth, A. et al.', 'FIDO 2.0 Web Authentication (WebAuthn)', 'W3C Recommendation', '2021'),
    ('Brandt, A. et al.', 'EMV Integrated Circuit Card Specifications for Payment Systems', 'EMVCo, Book 2', '2023'),
    ('PCI Security Standards Council', 'Payment Card Industry Data Security Standard (PCI DSS)', 'Version 4.0', '2022'),
    ('European Parliament and Council', 'Directive (EU) 2015/2366 on Payment Services (PSD2)', 'Official Journal of the European Union', '2015'),
    ('ISO/IEC', 'Information Security Management Systems — Requirements', 'ISO/IEC 27001:2022', '2022'),
    ('SWIFT', 'Customer Security Programme (CSP) — Security Controls', 'SWIFT Handbook', '2024'),
    ('IBM Security', 'Cost of a Data Breach Report 2024', 'IBM Corporation', '2024'),
    ('Verizon', 'Data Breach Investigations Report (DBIR) 2024', 'Verizon Enterprise', '2024'),
    ('OWASP Foundation', 'OWASP API Security Top 10 — 2023', 'OWASP', '2023'),
    ('Bangladesh Bank / SWIFT', 'Report on Cyber Heist Investigation (Bangladesh Bank)', 'Financial Sector Incident Analysis', '2016'),
    ('Kaspersky Lab', 'The Great Bank Robbery: Carbanak Cybergang', 'Securelist Research', '2015'),
    ('NIST', 'Digital Signature Standard (DSS)', 'FIPS 186-5', '2023'),
    ('NIST', 'Secure Hash Standard (SHS)', 'FIPS 180-4', '2015'),
    ('NIST', 'Guidelines for the Selection, Configuration, and Use of TLS Implementations', 'NIST SP 800-52 Rev. 2', '2019'),
    ('NIST', 'Recommendation for Pair-Wise Key Establishment Schemes Using Discrete Logarithm Cryptography', 'NIST SP 800-56A Rev. 3', '2018'),
    ('Merkle, R. C.', 'A Digital Signature Based on a Conventional Encryption Function', 'CRYPTO 1987, LNCS', '1988'),
    ('Nakamoto, S.', 'Bitcoin: A Peer-to-Peer Electronic Cash System', 'Bitcoin Whitepaper', '2008'),
    ('Cromwell, R. et al.', 'Corda: An Introduction', 'R3 Whitepaper', '2016'),
    ('Diffie, W.; Hellman, M.', 'New Directions in Cryptography', 'IEEE Transactions on Information Theory', '1976'),
    ('Miller, V. S.', 'Use of Elliptic Curves in Cryptography', 'CRYPTO 1985, LNCS', '1986'),
    ('Koblitz, N.', 'Elliptic Curve Cryptosystems', 'Mathematics of Computation', '1987'),
    ('Bellare, M.; Namprempre, C.', 'Authenticated Encryption: Relations among Notions and Analysis of Generic Composition Paradigm', 'ASIACRYPT 2000, LNCS', '2000'),
    ('Dolev, D.; Yao, A.', 'On the Security of Public Key Protocols', 'IEEE Transactions on Information Theory', '1983'),
    ('Open Banking UK', 'Open Banking Standard — Security Profile', 'Open Banking Implementation Entity', '2023'),
    ('NIST', 'Post-Quantum Cryptography Standardization', 'NIST CSRC — ML-KEM, ML-DSA', '2024'),
    ('Bernstein, D. J.', 'Curve25519: New Diffie-Hellman Speed Records', 'PKC 2006, LNCS', '2006'),
    ('IEEE', 'IEEE Standard Specifications for Public-Key Cryptography — Amendment 1: ECIES', 'IEEE 1363a', '2004'),
    ('Dennis, F. et al.', 'A Comprehensive Survey on Electronic Banking Security', 'Computers & Security', '2020'),
    ('Aloul, F. et al.', 'Online Banking Security Measures and Vulnerabilities', 'IEEE Security & Privacy', '2015'),
    ('Cremers, C. et al.', 'The TAMARIN Prover for the Symbolic Analysis of Security Protocols', 'CAV 2013, LNCS', '2013'),
    ('Blanchet, B.', 'Modeling and Verifying Security Protocols with the Applied Pi Calculus and ProVerif', 'Foundations and Trends in Privacy and Security', '2016'),
]
